input { http { port => 8085 } }
filter { json { source => "message" } }
output {
  elasticsearch { hosts => ["elasticsearch:9200"]; index => "pac-ai-%{+YYYY.MM.dd}" }
  stdout { codec => rubydebug }
}
