events { }

http {
  upstream orchestrator {
    server orchestrator:8000;
  }

  upstream ohif {
    server ohif:80;
  }

  server {
    listen 443 ssl;
    ssl_certificate     /etc/ssl/certs/dev-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/dev-selfsigned.key;

    location /api/ {
      proxy_pass http://orchestrator;
    }

    location /viewer/ {
      proxy_pass http://ohif;
    }
  }
}
